-- MySQL Script generated by MySQL Workbench
-- Tue Mar 21 15:11:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Авторы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Авторы` (
  `id_Авторы` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Авторы`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Книги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Книги` (
  `id_Книги` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `year_of_publication` YEAR(10) NOT NULL,
  `Авторы_id_Авторы` INT NOT NULL,
  PRIMARY KEY (`id_Книги`),
  INDEX `fk_Книги_Авторы1_idx` (`Авторы_id_Авторы` ASC) VISIBLE,
  CONSTRAINT `fk_Книги_Авторы1`
    FOREIGN KEY (`Авторы_id_Авторы`)
    REFERENCES `mydb`.`Авторы` (`id_Авторы`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Паспорт`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Паспорт` (
  `id_Паспорт` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nation` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Паспорт`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Читатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Читатели` (
  `id_Читатели` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `Паспорт_id_Паспорт` INT NOT NULL,
  PRIMARY KEY (`id_Читатели`),
  INDEX `fk_Читатели_Паспорт_idx` (`Паспорт_id_Паспорт` ASC) VISIBLE,
  CONSTRAINT `fk_Читатели_Паспорт`
    FOREIGN KEY (`Паспорт_id_Паспорт`)
    REFERENCES `mydb`.`Паспорт` (`id_Паспорт`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Читальный_зал`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Читальный_зал` (
  `id_Читальный_зал` INT NOT NULL AUTO_INCREMENT,
  `titile` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Читальный_зал`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Хранение`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Хранение` (
  `Книги_id_Книги` INT NOT NULL,
  `Читальный_зал_id_Читальный_зал` INT NOT NULL,
  INDEX `fk_Хранение_Книги1_idx` (`Книги_id_Книги` ASC) VISIBLE,
  INDEX `fk_Хранение_Читальный_зал1_idx` (`Читальный_зал_id_Читальный_зал` ASC) VISIBLE,
  CONSTRAINT `fk_Хранение_Книги1`
    FOREIGN KEY (`Книги_id_Книги`)
    REFERENCES `mydb`.`Книги` (`id_Книги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Хранение_Читальный_зал1`
    FOREIGN KEY (`Читальный_зал_id_Читальный_зал`)
    REFERENCES `mydb`.`Читальный_зал` (`id_Читальный_зал`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Чтение`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Чтение` (
  `Читальный_зал_id_Читальный_зал` INT NOT NULL,
  `Читатели_id_Читатели` INT NOT NULL,
  INDEX `fk_Чтение_Читальный_зал1_idx` (`Читальный_зал_id_Читальный_зал` ASC) VISIBLE,
  INDEX `fk_Чтение_Читатели1_idx` (`Читатели_id_Читатели` ASC) VISIBLE,
  CONSTRAINT `fk_Чтение_Читальный_зал1`
    FOREIGN KEY (`Читальный_зал_id_Читальный_зал`)
    REFERENCES `mydb`.`Читальный_зал` (`id_Читальный_зал`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Чтение_Читатели1`
    FOREIGN KEY (`Читатели_id_Читатели`)
    REFERENCES `mydb`.`Читатели` (`id_Читатели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
